# Generated by Django 3.0.3 on 2020-09-04 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_mainmustbuy'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeid', models.IntegerField(default=1)),
                ('typename', models.CharField(max_length=32)),
                ('childtypenames', models.CharField(max_length=255)),
                ('typesort', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'FoodTypes',
            },
        ),
    ]
